name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up Git
        run: |
          git config user.name "Mattia Magi"
          git config user.email "mattia.magi91@gmail.com"
      - name: Determine the version
        id: determine_version
        run: |
          echo "::set-output name=version::${{ github.event.inputs.version }}"

      - name: Tag the commit
        run: |
          git tag -a "${{ steps.determine_version.outputs.version }}" -m "Version ${{ steps.determine_version.outputs.version }}"
          git push --follow-tags
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.determine_version.outputs.version }}
          release_name: Release ${{ steps.determine_version.outputs.version }}
          body: |
            Release ${{ steps.determine_version.outputs.version }}

            Add release notes here.
          draft: false
          prerelease: false