name: Release Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release:')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up Git
        run: |
          git config user.name "This Dot Open Source"
          git config user.email "opensource@thisdot.co"
      - name: Get tag
        id: get_tag
        run: |
          git branch --show-current
          git pull
          echo "version=v$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT
      - name: Tag the commit
        run: |
          next_version=${{ steps.get_tag.outputs.version }}
          git tag -a "$next_version" -m "Version $next_version"
          git push --follow-tags
      - name: Generate Changelog Diff
        id: changelog_diff
        run: |
          # Retrieve the previous release's tag name
          PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))

          # Set the output variable to make it available for later steps
          echo "changelog_diff=$(git diff --no-color --unified=0 "$PREVIOUS_TAG" HEAD -- CHANGELOG.md)" >> $GITHUB_OUTPUT
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.version }}
          release_name: Release ${{ steps.get_tag.outputs.version }}
          body: |
            Release ${{ steps.get_tag.outputs.version }}

            ${{ steps.changelog_diff.outputs.changelog_diff }}
          draft: false
          prerelease: false
