name: Version Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Set up Git
        run: |
          git config user.name "Mattia Magi"
          git config user.email "mattia.magi91@gmail.com"
      - name: Create a commit with new version and push it
        id: create_commit
        run: |
          git checkout -b release/$(npm version ${{ github.event.inputs.version }})
          echo "version=v$(npm pkg get version)" >> $GITHUB_OUTPUT
          git add ./package.json
          git log --oneline
          git push -u origin release/${{ steps.create_commit.outputs.version }}
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.create_commit.outputs.version }}
          title: "Release ${{ steps.create_commit.outputs.version }} Pull Request"
          body: "This pull request contains the updated package.json with the new release version"
          base: main